default_config:

logger:
  default: error
  logs:
    custom_components.gismeteo: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
debugpy:
  start: true
  wait: true

sensor:
  - platform: gismeteo
    monitored_conditions:
      - temperature
      - humidity

weather:
  - platform: gismeteo
